Issue#7_listeners_correction
SkirdaD/Calculator pull request #14
Opened 2023-02-17 16:51 UTC by SkirdaD

2023-02-17 16:56 UTC, SkirdaD commented
Сделал коммит. Вроде, неплохо получилось.

Я пока в другую папку не вынес. 
И да, я понял, что такое другой пакет. Сразу понятно стало, а то я думал, что это что-то сложнее, а это просто другая папка.

2023-02-17 17:22 UTC, SkirdaD commented
Выход вижу такой: Калькулятор, КалькуляторДата и ВьювХолдер сделать паблик.
И сами листенеры тоже. 
Сделаю и закоммичу.
А ты оценивай)

2023-02-17 22:15 UTC, russabit requested changes

2023-02-17 22:15 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +            button.setOnClickListener(new OnNumberButtonsClickListener(calculator, viewHolder));
тебе действительно нужны 11 объектов КЛ-ра для каждой кнопки по отдельности? до этого был один и тот же

2023-02-18 07:09 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +            button.setOnClickListener(new OnNumberButtonsClickListener(calculator, viewHolder));
Понял. Проглядел.
А у меня уже не получится через анонимный класс? 
Получается только через локальную переменную.

2023-02-18 07:16 UTC, SkirdaD commented
Посмотри коммит. Мне не нравится, что появилась новая локальная переменная.

2023-02-18 07:25 UTC, merged

2023-02-18 07:25 UTC, russabit commented
> Посмотри коммит. Мне не нравится, что появилась новая локальная переменная.

это как раз исправится в следующей главе - тут нужна инъекция зависимостей.