create_all_listeners
SkirdaD/Calculator pull request #15
Opened 2023-02-18 15:36 UTC by SkirdaD

2023-02-18 15:46 UTC, SkirdaD commented
Сделал.
Смотри метод ::showDivisionByZeroError.
Я его реализовал только в кнопке минус (специально в минусе, чтоб ты видел изменение кода, а не его создание). 
Короче) Надо нажать "5 / 0 -".
Но что-то я там намудрил с ним.
Зато всё остальное вроде норм. Смотри короче)

И я там метод ::changeSizeText попытался перегрузить)

2023-02-19 01:51 UTC, russabit requested changes

2023-02-19 01:51 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculator.java
> +    private boolean isAfterOperation;
что это за название которое ни о чём не говорит? что после операции? когда надо лезть в код и смотреть как переменная используется чтобы понять что она делает - это значит что она плохо названа

2023-02-19 01:51 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                setOnClickListener(new OnMinusButtonClickListener(calculator, viewHolder, this));
красиво же стало в активити? то-то же. вот только я уже писал, что одна строчка не должна выполнять две операции одновременно - как тут: сеттинг листенера и тут же его создание внутри. это две разные логические операции, разнеси их отдельно. что всё можно разделить разделяй. не бойся вводить новые переменные как ты писал раньше - они как минимум дают тебе шанс назвать что получилось

подсказка (забегая вперёд) - потому что потом создание мы будем выносить отдельно в класс-завод, отвечающий за создание объектов, нужных активити, отсюда и название шаблона - фабрика. и если инстанцирование будет в одном месте, тебе же легче будет его вынести

2023-02-19 01:51 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivityExtensionMethods.java
> +    public static String formattingWholeDoubleAsInt(String text) {
опять английский, сколько можно - форматтинг это существительное, а не глагол

2023-02-19 01:51 UTC, russabit commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnAllCleanButtonClickListener.java
> +        calculator.setResult(0);
если пишешь и видишь что у тебя повторяются операции, значит надо вынести в метод - плюсом назвать его чтобы понятно, типа стеретьВсё() -   wipeData() / eraseData() и т.п.

2023-02-19 01:51 UTC, russabit commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
>              } else return;
здесь мне давно глаза мозолило - по сути у тебя одна операция `text = text + x`, где х - это взаимное отображение айдишника кнопки с соответствующей ей операцией. значит у нас есть маппинг "кнопка +" это "операция плюс", "кнопка делить" это "операция делить" и т.п. (кроме кнопки запятой, она особая). значит это отображение надо отдельно сохранить и как-то назвать. 

какие у нас классы позволяют хранить отображения? правильно, хэшмапа.

таким образом, сделай мапу с ключом id кнопки, и тогда сможешь написать общий случай через
`text = text + map.get(v.getId())`, а случай точки-запятой (благо он единственный) можно решать через  null.

вообще клёвая задача, тут тебе и хэшмапу придётся повторить, которую постоянно спрашивают на собесах и то как методы хорошо проектировать (многоуровневые if-ы это дурно пахнущий код), и мозгами подумать :)

2023-02-19 01:57 UTC, russabit commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
>              } else return;
такое же маппинг кстати у Calculator::operate - он взаимно отображает Operation и операцию, но там посложнее потому что значением будет не стринга как выше, а кусок кода, т.е. (лямбда?), но если поймёшь предыдущую, то тоже можно сделать будет (_наверное_)

2023-02-19 11:07 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
>              } else return;
Смотри коммит. 
Сделал мапы.
Но с мапой в ::operate выходит предупреждение Unboxing of 'operationMap.get(currentOperation)' may produce 'NullPointerException'

Посмотри. Я правильно вообще понял тебя. Но, всё работает)

2023-02-19 12:03 UTC, russabit requested changes

2023-02-19 12:03 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculator.java
> +        operationMap.put(Operation.NONE, var);
чё за бред? нам надо одну операцию посчитать при вызове метода, ты суёшь в мапу вообще все операции и все они вычисляются и остаются лежать в калькуляторе. потом когда снова вызываем оперейт опять все операции считаются и кладутся в мапу, ладно хотя бы что перезаписываются благодаря ключам, а не мапа раздувается. но зачем нам столько лишнего?

2023-02-19 12:03 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
>          viewHolder.getMainTextView().setText("0"); // так сделано, пока нет шареда
чё это тут делает посередине между инстанцированием?

2023-02-19 12:03 UTC, russabit commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
> +        buttonValues.put(R.id.button9, "9");
здесь ещё хуже, при нажатии каждой цифры создаётся новая хэшмапа + 10 значений кладётся??? типа мы быстро набираем миллион, у нас 60 лишних операций производится?

2023-02-19 12:05 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculator.java
> +        operationMap.put(Operation.NONE, var);
ещё есть EnumMap как раз для случая когда ключи это энамы, я ни разу не пробовал но кажется должна подойти

2023-02-19 13:16 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
>          viewHolder.getMainTextView().setText("0"); // так сделано, пока нет шареда
Упс)

2023-02-19 13:17 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
> +        buttonValues.put(R.id.button9, "9");
Вроде переделал

2023-02-19 13:19 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/Calculator.java
> +        operationMap.put(Operation.NONE, var);
А с этим я не понимаю.
В нее нужно положить что-то другое. Но не понимаю что

2023-02-19 15:06 UTC, SkirdaD commented
Вот последний коммит. Вернул старый Калькулятор.
Плюс нашел баг в лисентнере цифр. Исправил.
Плюс добавил строку в мапу с точкой дробных числе. Только для наглядности, что тут точка тоже обрабатывается.

2023-02-19 15:07 UTC, SkirdaD commented
Дальше не знаю, за что браться. Жду тогда ваших указаний, мой господин.

2023-02-19 15:09 UTC, SkirdaD commented
Может точку в отдельный листенер вынести?

2023-02-19 15:24 UTC, russabit commented on app/src/main/java/slirdad/calculator/OnClickListeners/OnNumberButtonsClickListener.java
> +    {
тут можно без блока через двойные скобки на месте объявления мапы сделать. либо через Map.of(), отдельно не очень хорошо смотрится.

2023-02-19 16:30 UTC, SkirdaD commented
Смотри коммит и заливай тогда его, если всё ок.

2023-02-20 06:00 UTC, merged