issue_1
SkirdaD/Calculator pull request #2
Opened 2023-01-06 12:06 UTC by SkirdaD

2023-01-09 14:39 UTC, russabit requested changes

2023-01-09 14:39 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void operation() {
operation - это существительное, а не глагол

2023-01-09 14:39 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
любые числа должны быть константами (чтобы у каждой было имя которое описывает что она собой представляет) - по макконелу

2023-01-09 14:39 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
как и любой текст

2023-01-09 14:39 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
почему выбрал протектид? собираешься наследоваться и переопределять?

2023-01-09 14:39 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
эти кликлистенеры не вынес отдельно

2023-01-11 18:32 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
Вообще все? Или только те, которые используются в логической части программы?
Я имею в виду, когда я зануляю переменную или что-то типа того. Такие же не надо?
типа var1 = 0;

2023-01-11 18:33 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
По тексту понятно. Я перенесу весь текст в values string.

2023-01-11 18:35 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
Я не до конца понимаю. По сути, в моей программе (на данный момент) будет работать с любым модификатором. Мне нужно выбрать максимально закрытый или открытый, который может быть в поставленной задаче?

2023-01-11 18:35 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
Я не понял тебя. Куда мне их нужно было вынести? По моему, не было разговора о них.

2023-01-11 18:41 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
lastOperation = savedInstanceState.getInt("lastOperation");

Этот текст тоже так сделать или в случае ключа допускается?

2023-01-12 04:36 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
зануляешь в каком смысле? 0 или null ? )

2023-01-12 04:40 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
хорошо что спросил, их вообще лучше в enum'e описать

2023-01-12 04:54 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
давай разбираться. 

на примере кто клиент (кто вызывает этот метод) лучше всего понятно какой модификатор ставить. ты поставил протектид посмотрев на остальные андроидовские методы выше - онКриэйт и т.п.. но кто их вызывает? (отдельный вопрос) и почему они протектид?

теперь смотри на свои методы changeSizeText(), operation(). кто их вызывает? кто клиент?

2023-01-12 04:56 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
пункт 6 перечитай, тут у тебя сеттится и создаётся в одном месте

2023-01-12 04:58 UTC, russabit commented
<img width="813" alt="Screenshot 2023-01-12 at 3 57 33 pm" src="https://user-images.githubusercontent.com/50712640/211980619-10f745b6-4959-4c87-a9fb-1b26fe91558b.png">

у тебя есть вот такая линия, называется хард врап, она ограничивает ширину строки, у тебя не должно ничего за неё заходить - это к оформлению

2023-01-12 19:13 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
0

2023-01-12 19:15 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
Хорошо) Я все ключи перенесу в энам. Но я так и не понимаю, почему надо так))
Если я создам энам, то ведь названия будут те же. То есть визуально будет так же. Для чего это нужно?

2023-01-12 19:25 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
андроидовские методы вызывает система. Ну, наверное, сама активити.
Почему протектид? Что бы наследники могли использовать эти методы. Но в данном контексте я не очень понимаю.

мои методы тоже как бы вызываются объектом моей активити

2023-01-12 19:26 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
то ли я не понял твой вопрос, то ли просто туплю)

2023-01-12 19:33 UTC, SkirdaD commented
И у меня вопрос.
вот строка
buttonNum1 = (Button) findViewById(R.id.button1);
Иногда, когда запускаю андроид студио, студия пишет замечания. Типа удали "(Button)". А иногда не ругается, типа всё норм. 
Так надо тут использовать сужение типа или нет?
![Снимок](https://user-images.githubusercontent.com/121316397/212163515-d427f332-443b-4be8-ba03-3d6119fed434.JPG)

2023-01-12 19:47 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
Понял. Тогда вопрос. Как принято писать. Сначала все лисенеры, а потом все их засетить. Или лисенер, сразу его сечу, потом второй пишу, его сечу и т. д.?

2023-01-12 19:48 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
И опять же вопрос) Так нужно делать, потому что так принято или есть какая-то более высокая цель?)

2023-01-12 19:49 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
короче) посмотришь, как я сделал и скажешь

2023-01-12 20:23 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
Не понимаю я энамы(((
Вот так я должен был сделать?
![изображение](https://user-images.githubusercontent.com/121316397/212172330-b6b29f2d-d95b-492b-8822-b808d5253998.png)
И как потом ими пользоваться? Keys.RESULT.name
Или к энамам подвесить стринги ( RESULT ("Result"), а потом ими пользоваться через геттер?

2023-01-12 20:45 UTC, SkirdaD commented
хард врап подогнал. А комменты могут за эту линию выходить?

2023-01-13 10:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
обещания это хорошо, но где новые коммиты? обсуждать можно долго

2023-01-13 12:04 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
да, точно, инамы только интовые ADDITION, SUBTRACTION и т.п., стринги просто константами

2023-01-13 12:14 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    protected void changeSizeText() {
ладно пока забей, потом увидишь на другом примере.

2023-01-13 12:17 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +                    Toast.makeText(getApplicationContext(), "ОШИБКА ДЕЛЕНИЯ НА НОЛЬ", Toast.LENGTH_LONG).show();
хз короче я уже сам потерялся, без новых коммитов даже не понятно о чём речь

2023-01-13 12:20 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
напиши хоть как сам думаешь будет лучше и запуш, посмотрим. высокая цель научить тебя писать хороший код

2023-01-13 12:22 UTC, russabit commented
> хард врап подогнал. А комменты могут за эту линию выходить?

нет, делай их в несколько строк если они такие длинные

2023-01-13 12:23 UTC, russabit commented
> Так надо тут использовать сужение типа или нет?

хз, студия тупит

2023-01-13 12:26 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
пункт 6 ты по видимому не перечитал ))

2023-01-13 19:45 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
Перечитал 100 раз)
Я вынес их отдельно.
Я понял, что ты ведешь к тому, что их куда-то надо переместить. Я не понимаю куда)

2023-01-13 20:43 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
Я в принципе всё поправил. Мне только осталось переделать под констрейт. Вот разбираюсь. Доделаю и сразу коммит сделаю.

2023-01-14 08:17 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        buttonPlus.setOnClickListener(view -> {
как минимум вынося отдельно ты даёшь им названия, поэтому кстати невынесенные классически называются анонимными классами

2023-01-14 08:18 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        if (textMainField.length() < 8) {
в реальной рабочей обстановке лучше делать много коммитов и сразу их пушить чем затягивать работу чем-то одним. так что давай запушивай то что уже сделал, а констрейт следующим коммитом сделаешь. он самый неважный сейчас из всех замечаний

2023-01-16 13:06 UTC, russabit commented
с констрейнтом хорошо получилось, красава что быстро разобрался, потом детальнее посмотрю чё там как, но на первый взгляд норм.

запустил потыкал, увидел баг: у тебя при нажатии на равно исчезает вверху выражение

комменты так и не поправил, не должны заходить за хардврап, + ещё раз у тебя они проясняют логику (а не к багам относятся), то лучше пиши их в формате документации выше над методом ( /* продолжение дествий после нажатия на равно */)

давай эти мелочи поправь, я аппрувну, вольём в мастре и начнём нормальный рефакторинг в новом ишью

2023-01-16 15:04 UTC, SkirdaD commented
Ха-ха) Это не баг, а фича)))
Я специально так сделал)) Так работает калькулятор на винде.
Мне тоже не нравится. Поправлю в более хороший вид.

2023-01-16 16:33 UTC, SkirdaD commented
Всё. Запушил. Всё доделал. Мою фичу/баг исправил на более хороший вариант. Пришлось ввести лишний стринг. Я его ввел местно, т.к. он по сути нигде больше не фигурирует.

2023-01-18 00:05 UTC, merged