AboutAppActivity
SkirdaD/Calculator pull request #27
Opened 2023-02-27 20:56 UTC by SkirdaD

2023-02-27 20:59 UTC, SkirdaD commented
Посмотри. Вообще, что скажешь? Сделал, как в старт андроиде)
Конечно, возник вопрос, куда положить новый класс.
Я думаю, что в папку UI. Но там должна быть еще иерархия. Наверное, по активити.

2023-02-28 14:37 UTC, russabit commented
молодец, только открывать новую активити ради небольшого экрана с информацией нету смысла. переделывай на фрагмент

2023-02-28 14:51 UTC, SkirdaD commented
> молодец, только открывать новую активити ради небольшого экрана с информацией нету смысла. переделывай на фрагмент

Понял. А по поводу Клина?

2023-03-01 19:33 UTC, SkirdaD commented
Смотри.
Что-то тяжело мне дался фрагмент)
Не понимаю, почему фрагмент фоном под кнопками пошел. Посмотри. Там голубой фон для наглядности.

2023-03-02 01:03 UTC, russabit commented
> > молодец, только открывать новую активити ради небольшого экрана с информацией нету смысла. переделывай на фрагмент
> 
> Понял. А по поводу Клина?

по поводу клина да, все правильно,под каждый экран свои папки

2023-03-02 01:05 UTC, russabit commented
> Смотри. Что-то тяжело мне дался фрагмент) Не понимаю, почему фрагмент фоном под кнопками пошел. Посмотри. Там голубой фон для наглядности.

с этим я и хотел посмотреть додумаешься или нет. я всё ещё в тебя верю, т.к. если подскажу то уже не будет считаться

2023-03-02 06:13 UTC, SkirdaD commented
Как скрыть Активити под фрагментом я не нашел. 
Поэтому единственное, что пришло в голову, что сам калькулятор тоже должен быть фрагментом в мэйнактивити.

2023-03-02 06:31 UTC, russabit commented
> Как скрыть Активити под фрагментом я не нашел. Поэтому единственное, что пришло в голову, что сам калькулятор тоже должен быть фрагментом в мэйнактивити.

молодец, догадался. тогда ты знаешь что делать

2023-03-02 11:32 UTC, russabit reviewed
жду переписывания на фрагмент

2023-03-02 11:32 UTC, russabit commented on app/build.gradle
> +        viewBinding true
ух ты, это ты с чего решил?

2023-03-02 11:32 UTC, russabit commented on app/src/main/res/menu/main_activity_menu.xml
> +        android:title="Item" />
можешь сразу все добавить, но чтобы в активити они обрабатывались пока нету реализации через показ тоста "экран в разработке", иначе будет падать

2023-03-02 15:58 UTC, SkirdaD commented on app/build.gradle
> +        viewBinding true
Я, кстати, понятия не имею, что это. И как произошло)
Видимо, когда я использовал шаблон

2023-03-02 16:03 UTC, SkirdaD commented on app/build.gradle
> +        viewBinding true
Убрать?
Если убрать, то нельзя запустить приложение

2023-03-02 19:39 UTC, SkirdaD commented
Короче) Коммит. И я им доволен)
Работает, по крайней мере.

У меня вопрос (ничего внятного не нагуглил).
  1.   Для каждой манипуляции нужно создавать новый `getSupportFragmentManager().beginTransaction()`???
Т.к. если использовать один на для всего, то не дает вызвать другой фрагмент. Пишет, что коммит уже сделан.
Можешь объяснить этот момент?

  2.   В бэкстэк передаю стринг. Я в него провалился и вижу, что это имя. Но не понимаю, зачем нужно имя.

2023-03-02 19:41 UTC, SkirdaD commented
И я уже с ужасом думаю, как я буду сливаться этой веткой с MVVM)))
Там будет конфликт на конфликте.

2023-03-02 19:48 UTC, SkirdaD commented
И я так понимаю, что МэйнАктивити можно подчистить как-нибудь. Ну типа холдера. Или нет?

2023-03-03 00:13 UTC, russabit commented on app/build.gradle
> +        viewBinding true
что за шаблон?

2023-03-03 02:21 UTC, russabit commented
так, дизайн экрана хороший, мне нравится

всё остальное нет )) давай получше обрисую как строится работа с фрагментами и что я хочу от тебя увидеть:

- калькулятор - главный экран, на него возвращаемся кнопкой назад с любого другого экрана
- в выпадающем меню у нас 4 экрана, первый из них "калькулятор", а не "о приложении". у тебя же оба "о приложении" и нету калькулятора
- при переходе на другой фрагмент, он не скрывается ( как ты делаешь hide()), а удаляется или реплейсится, как тебе удобнее, главное чтобы предыдущий уничтожался, даже калькулятор (пока что так, потом требования могут измениться когда начнёшь писать игру, там калькулятор будет переиспользоваться и это будет интересная задача)
- при инициализации первого экрана ты не создаёшь остальные, может пользователь вообще 99% времени не будет в них переходить, тогда и смысла инициализировать нету. причём они же заново пересоздаются ещё при каждом перевороте экрана

вроде всё. и разберись с иерархией папок, почему у тебя оба фрагмента лежат на том же уровне что и активити? они равнозначны?

2023-03-03 02:28 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/UI/MainActivity.java
> +        aboutAppFragment = new AboutAppFragment();
я про это, зачем тебе создавать сразу и второй экран если на него ещё не перешли?

2023-03-03 02:28 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/UI/MainActivity.java
> +                add(R.id.fragment, calculatorFragment).commit();
тут ты же только первый фрагмент кладёшь

2023-03-03 02:28 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/UI/MainActivity.java
> +        } else if (item.getItemId() == R.id.about_app2) {
почему "о приложении 2" ? будет два экрана?

2023-03-03 02:28 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/UI/MainActivity.java
> +                    add(R.id.fragment, aboutAppFragment).addToBackStack("aboutApp").commit();
вместо hide() и add() лучше использовать replace(), тебе разве нужен калькулятор когда ты на экране "о приложении"?

2023-03-03 07:52 UTC, SkirdaD commented on app/build.gradle
> +        viewBinding true
![изображение](https://user-images.githubusercontent.com/121316397/222662870-2ea63bed-60c0-47dd-bee3-aaacd66f26e9.png)

2023-03-03 07:52 UTC, SkirdaD commented on app/build.gradle
> +        viewBinding true
больше я никуда не лазил)

2023-03-03 07:56 UTC, SkirdaD commented
> калькулятор - главный экран, на него возвращаемся кнопкой назад с любого другого экрана

Так и было.

> * в выпадающем меню у нас 4 экрана, первый из них "калькулятор", а не "о приложении". у тебя же оба "о приложении" и нету калькулятора

Можно поспорить)? Я считаю, его там быть не должно. Чтобы он оставался как бы базовым.
Сейчас по моему коду так и есть. Из меню выбираешь о приложении, а потом нажимаешь назад и всё ок.

Всё остальное переделал.

2023-03-03 07:56 UTC, SkirdaD commented
> Короче) Коммит. И я им доволен) Работает, по крайней мере.
> 
> У меня вопрос (ничего внятного не нагуглил).
> 
>     1. Для каждой манипуляции нужно создавать новый `getSupportFragmentManager().beginTransaction()`???
>        Т.к. если использовать один для всего, то не дает вызвать другой фрагмент. Пишет, что коммит уже сделан.
>        Можешь объяснить этот момент?
> 
>     2. В бэкстэк передаю стринг. Я в него провалился и вижу, что это имя. Но не понимаю, зачем нужно имя.

И почему ты игнорируешь мои вопросы?))

2023-03-03 07:59 UTC, russabit commented
> > калькулятор - главный экран, на него возвращаемся кнопкой назад с любого другого экрана
> 
> Так и было.
> 
> > * в выпадающем меню у нас 4 экрана, первый из них "калькулятор", а не "о приложении". у тебя же оба "о приложении" и нету калькулятора
> 
> Можно поспорить)? Я считаю, его там быть не должно. Чтобы он оставался как бы базовым. Сейчас по моему коду так и есть. Из меню выбираешь о приложении, а потом нажимаешь назад и всё ок.
> 
> Всё остальное переделал.

да без проблем, мне главное чтобы калькулятор реплейсился вместо хайда, остальное не суть

2023-03-03 08:03 UTC, SkirdaD commented
Смотри коммит.
И у меня вопрос. Если находясь во фрагменте  эбаутАпп и через меню еще несколько раз нажать эбаут апп, то все они попадают в стэк.
Это как решить? Убрать в текущем фрагменте пункт меню, или как-то можно ограничить количество в стэке?

2023-03-03 08:03 UTC, russabit commented
> > Короче) Коммит. И я им доволен) Работает, по крайней мере.
> > У меня вопрос (ничего внятного не нагуглил).
> > ```
> > 1. Для каждой манипуляции нужно создавать новый `getSupportFragmentManager().beginTransaction()`???
> >    Т.к. если использовать один для всего, то не дает вызвать другой фрагмент. Пишет, что коммит уже сделан.
> >    Можешь объяснить этот момент?
> > 
> > 2. В бэкстэк передаю стринг. Я в него провалился и вижу, что это имя. Но не понимаю, зачем нужно имя.
> > ```
> 
> И почему ты игнорируешь мои вопросы?))

теряю по пути. как ты используешь один и тот же я не понял, покажи пример. 

про бэкстек тебе пока можно вообще не запариваться, особенно учитывая что у тебя один базовый фрагмент и остальные на него возвращают. переопредели onBackPressed чтобы из доп фрагментов выходил на главный фрагмент, а из главного выходил из приложения и всё

2023-03-03 08:04 UTC, russabit commented
> Смотри коммит. И у меня вопрос. Если находясь во фрагменте эбаутАпп и через меню еще несколько раз нажать эбаут апп, то все они попадают в стэк. Это как решить? Убрать в текущем фрагменте пункт меню, или как-то можно ограничить количество в стэке?

да убирай из меню просто пока

2023-03-03 08:08 UTC, SkirdaD commented
> теряю по пути. как ты используешь один и тот же я не понял, покажи пример.


![изображение](https://user-images.githubusercontent.com/121316397/222666103-63c612c4-a7c7-4d4d-83e2-37b9836c2127.png)

2023-03-03 08:55 UTC, russabit commented
> > теряю по пути. как ты используешь один и тот же я не понял, покажи пример.
> 
> ![изображение](https://user-images.githubusercontent.com/121316397/222666103-63c612c4-a7c7-4d4d-83e2-37b9836c2127.png)

лол, ты путаешь фрагмент мэнэджер и транзакцию. фрагмент менеджер один можно использовать, но смысла все равно нету раз он геттером достаётся. а транзакция это последовательный вызов ::begin add/hide/replace// ::commit

2023-03-03 20:03 UTC, SkirdaD commented
Коммит.

2023-03-06 08:34 UTC, SkirdaD commented
Смотри коммит.
Что дальше?
Кнопку оценить приложение пока не трогаю?
Трогаю написать разработчикам? Пока не понимаю, как отправить мэйл. Мне его надо самому отправить или посредством другого приложения?

2023-03-06 09:57 UTC, russabit commented
> Смотри коммит. Что дальше? Кнопку оценить приложение пока не трогаю? Трогаю написать разработчикам? Пока не понимаю, как отправить мэйл. Мне его надо самому отправить или посредством другого приложения?

да оценивать и негде потому что не выложено же ещё на Гугл плей) 
да, как написать разработчикам изучи какие есть варианты (я знаю только один через интент) и как работает и предложи, вместе выберем. 

ещё ссылку на этот гитхаб типа "сделайте это приложение лучше прислав нам ваш пулл реквест, репозиторий тут (ссылка-кнопка)"

2023-03-06 12:13 UTC, SkirdaD commented
> ещё ссылку на этот гитхаб типа "сделайте это приложение лучше прислав нам ваш пулл реквест, репозиторий тут (ссылка-кнопка)"

Мы же хотели "Смотреть исходный код".

2023-03-06 13:54 UTC, russabit commented
> > ещё ссылку на этот гитхаб типа "сделайте это приложение лучше прислав нам ваш пулл реквест, репозиторий тут (ссылка-кнопка)"
> 
> Мы же хотели "Смотреть исходный код".

да точно, так и лучше

2023-03-06 19:03 UTC, SkirdaD commented
> да, как написать разработчикам изучи какие есть варианты (я знаю только один через интент) и как работает и предложи, вместе выберем.

Смотри. Тоже сделал через интент.

Другой способ, который я нашел очень сложный. Суть в чем... Через интент мы просто переходим в почтовое приложение, а второй способ заключается в том, чтобы прямо из приложения отправить мэйл. Но! Там надо будет вводить логин и пароль для отправки (Ты стал бы в калькуляторе вводить свой логин и пароль????) И сработает только если почта клиента `gmail`.

Либо. Реализовать другой подход. Тоже отправка прямо из приложения. Но письмо будет анонимным (автор может только в теле письма написать свой обратный мэйл, если захочет) и САМОЕ ГЛАВНОЕ в коде придется указать свой логин и пароль от ящика. И как все пишут особо его не спрячешь.

2023-03-06 20:09 UTC, SkirdaD commented
Нашел баг. При повороте на aboutApp вылетает. Я понимаю почему. Потому что нет входного параметра для конструктора. 
Если всё убрать, то при повороте опять на калькулятор переходит. 
Я так понимаю, что это ишью про сохранение параметров. Пока не буду делать

2023-03-06 23:51 UTC, russabit commented
> > да, как написать разработчикам изучи какие есть варианты (я знаю только один через интент) и как работает и предложи, вместе выберем.
> 
> Смотри. Тоже сделал через интент.
> 
> Другой способ, который я нашел очень сложный. Суть в чем... Через интент мы просто переходим в почтовое приложение, а второй способ заключается в том, чтобы прямо из приложения отправить мэйл. Но! Там надо будет вводить логин и пароль человека, который пишет письмо, для отправки (Ты стал бы в каком-то калькуляторе вводить свой логин и пароль????) И сработает только если почта клиента `gmail`.
> 
> Либо. Реализовать другой подход. Тоже отправка прямо из приложения. Но письмо будет анонимным (автор может только в теле письма написать свой обратный мэйл, если захочет) и САМОЕ ГЛАВНОЕ в коде придется указать свой логин и пароль от ящика. И как все пишут особо его не спрячешь.

ну и хорошо, зато теперь знаем что другие варианты точно не подходят

2023-03-06 23:52 UTC, russabit commented
> Нашел баг. При повороте на aboutApp вылетает. Я понимаю почему. Потому что нет входного параметра для конструктора. Если всё убрать, то при повороте опять на калькулятор переходит. Я так понимаю, что это ишью про сохранение параметров. Пока не буду делать

по сути да, но вообще такие вещи сразу надо писать, это как бы подразумевается с любой фичой чтобы работало всегда, но раз сделал отдельно то и ладно (делай параллельно ради конфликтов)

2023-03-07 02:50 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +        Button viewGithubButton = (Button) view.findViewById(R.id.go_to_github_button);
уже забыл что-ли куда мы вьюхи выносим?

2023-03-07 02:50 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
куда все стринги вставляем?

2023-03-07 02:50 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/CalculatorFragment/UI/CalculatorFragmentLogicHolder.java
> +package slirdad.calculator.MainActivity.Domain.CalculatorFragment.UI;
фрагмент - это не домен активити, это просто то, что внутри него лежит. а то у тебя получается внутри домена лежит UI

2023-03-07 05:39 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/CalculatorFragment/UI/CalculatorFragmentLogicHolder.java
> +package slirdad.calculator.MainActivity.Domain.CalculatorFragment.UI;
Я отталкивался о того, что домен  - это бизнес логика.
И считаю, что фрагменты и есть бизнес логика.

Так, где я ошибся?
У каждого фрагмента и активити должны быть свои папки. 
Тогда получается, что папка калькуляторфрагмент и эбаутАппФрагмент должны лежать там же, где и активити

2023-03-07 05:40 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +        Button viewGithubButton = (Button) view.findViewById(R.id.go_to_github_button);
Нет, не забыл)
Как раз хотел спросить. Думал, что выносить нужно, когда совсем много.

2023-03-07 05:41 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +        Button viewGithubButton = (Button) view.findViewById(R.id.go_to_github_button);
Но по логике, там может появиться еще что-нибудь)
Поэтому правильный рефакторинг нужно сразу делать, чтоб потом не переделывать.

2023-03-07 05:42 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/CalculatorFragment/UI/CalculatorFragmentLogicHolder.java
> +package slirdad.calculator.MainActivity.Domain.CalculatorFragment.UI;
Мне нужно папки распотрошить или просто целиком перенести?

2023-03-07 06:25 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
Ты про ресурсы?
У нас же там с ними не работало

2023-03-07 07:03 UTC, SkirdaD commented
Смотри. Наверное, не правильно папки раскидал

2023-03-07 18:47 UTC, SkirdaD commented
Создал ЛоджикХолдер и перенес туда часть кода. Пока в папку не определил. 
Снова не очень понимаю. Вроде бы нужно в папку UI. Но показывать фрагменты это как бы и есть бизнес логика МэйнАктивити. Или не  так?

2023-03-07 18:48 UTC, SkirdaD commented
И как быть с этими методами `onCreateOptionsMenu` и `onOptionsItemSelected`.
Они должны остаться в МэйнАктивити или их можно как-то перенести?

2023-03-07 19:32 UTC, SkirdaD commented
И хотел предложить русифицировать приложение. Смысла не вижу делать интерфейс на английском.

2023-03-07 23:58 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
куда выносили стринги в прошлые разы?

2023-03-08 00:01 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/CalculatorFragment/UI/CalculatorFragmentLogicHolder.java
> +package slirdad.calculator.MainActivity.Domain.CalculatorFragment.UI;
бизнес логика, это калькулятор, или возможность написать разрабам, или поменять язык, или игра, а фрагмент это как и активити просто компонент андроида. или суть твоего приложения по твоему показать экран? суть квартиры тогда иметь окно? а ванны - плитку?

2023-03-08 00:02 UTC, russabit commented
> И как быть с этими методами `onCreateOptionsMenu` и `onOptionsItemSelected`. Они должны остаться в МэйнАктивити или их можно как-то перенести?

давай разберемся тогда к чему они относятся. кто их вызывает и где они переопределяются?

2023-03-08 00:04 UTC, russabit commented
> 

да, сразу надо два языка делать, выделяй в ишью, будет экран с настройками, там же и смена темы на светлую, и тип точек и вот это вот всё

2023-03-08 21:12 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
А, ты про локальные переменные)

2023-03-08 21:24 UTC, SkirdaD commented
> > И как быть с этими методами `onCreateOptionsMenu` и `onOptionsItemSelected`. Они должны остаться в МэйнАктивити или их можно как-то перенести?
> 
> давай разберемся тогда к чему они относятся. кто их вызывает и где они переопределяются?

Эти методы вызываются автоматически самим Андроидом при запуске активити. Типа онКрейт.
То есть его вызывает активити?
Я провалился... сам супер метод в классе Активити лежит.

2023-03-08 23:36 UTC, russabit commented
> > > И как быть с этими методами `onCreateOptionsMenu` и `onOptionsItemSelected`. Они должны остаться в МэйнАктивити или их можно как-то перенести?
> > 
> > 
> > давай разберемся тогда к чему они относятся. кто их вызывает и где они переопределяются?
> 
> Эти методы вызываются автоматически самим Андроидом при запуске активити. Типа онКрейт. То есть его вызывает активити? Я провалился... сам супер метод в классе Активити лежит.

главное, что _самим андроидом при запуске активити_ . **как онкриэйт**. онкриэйт можно куда-то перенести? мы его куда-то перенесли?

2023-03-08 23:38 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
ох, значит продолжаем урок который я думал что прошли. эти стринги известны на этапе написания кода или (компайл тайме) или в рантайме?

2023-03-08 23:41 UTC, russabit commented
опять ты все напутал с клином. давай так, выпиши все классы и напиши у каждого что он делает и **где используется**, можешь со стрелочками - чтобы понять что где вложено. и вместе объединим

2023-03-09 05:03 UTC, SkirdaD commented
> > > > И как быть с этими методами `onCreateOptionsMenu` и `onOptionsItemSelected`. Они должны остаться в МэйнАктивити или их можно как-то перенести?
> > > 
> > > 
> > > давай разберемся тогда к чему они относятся. кто их вызывает и где они переопределяются?
> > 
> > 
> > Эти методы вызываются автоматически самим Андроидом при запуске активити. Типа онКрейт. То есть его вызывает активити? Я провалился... сам супер метод в классе Активити лежит.
> 
> главное, что _самим андроидом при запуске активити_ . **как онкриэйт**. онкриэйт можно куда-то перенести? мы его куда-то перенесли?

Нет. Понял)

2023-03-09 05:07 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
Известны на этапе написания.
И тут так же
![изображение](https://user-images.githubusercontent.com/121316397/223925878-1737d23a-4a77-4e32-b1a1-45f37a0b7612.png)


Я так же по аналогии сделал

2023-03-09 05:11 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity/Domain/AboutAppFragment/UI/AboutAppFragment.java
> +                (new Intent(Intent.ACTION_VIEW, Uri.parse("https://github.com/SkirdaD/Calculator")));
Или ты про отдельный класс?

2023-03-09 05:21 UTC, SkirdaD commented
> опять ты все напутал с клином. давай так, выпиши все классы и напиши у каждого что он делает и **где используется**, можешь со стрелочками - чтобы понять что где вложено. и вместе объединим

![image](https://user-images.githubusercontent.com/121316397/223927781-c61a1786-d2ba-4769-8015-e7413eab34c8.jpeg)

2023-03-10 12:42 UTC, russabit commented
> > опять ты все напутал с клином. давай так, выпиши все классы и напиши у каждого что он делает и **где используется**, можешь со стрелочками - чтобы понять что где вложено. и вместе объединим
> 
> ![image](https://user-images.githubusercontent.com/121316397/223927781-c61a1786-d2ba-4769-8015-e7413eab34c8.jpeg)

отлично, сразу видно ошибки, но ты сам их найдешь - выпиши теперь на большем листе в скобочках у каждого класса какие у него импорты и посмотри сходится или нет

2023-03-10 15:43 UTC, SkirdaD commented
![image](https://user-images.githubusercontent.com/121316397/224359726-3f330b47-ce37-4f78-affa-de1e4c275345.jpeg)

2023-03-10 16:25 UTC, russabit commented
> Вот. А что должно сходиться? Там, где пусто, значит ничего интересного) ![image](https://user-images.githubusercontent.com/121316397/224359726-3f330b47-ce37-4f78-affa-de1e4c275345.jpeg)

уже что-то вырисовывается. какие мысли по этому поводу ? учитывая что у тебя нету дата слоя вообще (он будет только у экрана с историей), то тебе всего лишь надо правильно организовать по папкам два экрана в одной активити, не нарушая при этом иерархию (что ты сделал раньше и из-за чего я вообще все это начал)

2023-03-10 16:29 UTC, SkirdaD commented
> уже что-то вырисовывается. какие мысли по этому поводу ? учитывая что у тебя нету дата слоя вообще (он будет только у экрана с историей), то тебе всего лишь надо правильно организовать по папкам два экрана в одной активити, не нарушая при этом иерархию (что ты сделал раньше и из-за чего я вообще все это начал)

Никаких мыслей) Я не понимаю, что я должен додумать. Попробуй меня как-нибудь подвести

2023-03-10 16:31 UTC, SkirdaD commented
Тут уже неправильно?
![изображение](https://user-images.githubusercontent.com/121316397/224370721-789f5ded-f2c8-47cd-b7af-666e65f77535.png)

2023-03-10 17:05 UTC, russabit commented
> Тут уже неправильно? Наверное фрагменты должны быть внутри где-то. Ведь может быть еще одна активити и у нее свои слои будут ![изображение](https://user-images.githubusercontent.com/121316397/224370721-789f5ded-f2c8-47cd-b7af-666e65f77535.png)

ты открой тогда хоть папки все чтобы мне понятно было что во фрагментах лежит. 

по сути - опять нет. у тебя стрелочки на первом листе показывают иерархию. здесь же тупо всё в куче лежит.

2023-03-10 17:07 UTC, russabit commented
да, фрагмент должны быть внутри где-то. внутри чего? у тебя только один вариант и ты умудряешься его в упор не видеть

2023-03-10 17:07 UTC, SkirdaD commented
> ты открой тогда хоть папки все чтобы мне понятно было что во фрагментах лежит.

![изображение](https://user-images.githubusercontent.com/121316397/224378518-7afbb76e-d01e-4288-b005-770bed9cab77.png)

2023-03-10 17:08 UTC, SkirdaD commented
> да, фрагмент должны быть внутри где-то. внутри чего? у тебя только один вариант и ты умудряешься его в упор не видеть

Ну, фрагменты раньше лежали в UI Activity, но ты сказал, что не так

2023-03-10 17:25 UTC, russabit commented
> > ты открой тогда хоть папки все чтобы мне понятно было что во фрагментах лежит.
> 
> ![изображение](https://user-images.githubusercontent.com/121316397/224378518-7afbb76e-d01e-4288-b005-770bed9cab77.png)

уже лучше. только фрагмент это не UI, он же человек которые отдельно из полочек собирает. ui это в данном случае холдеры и екстенгшены (по моему, тут можно спорить до бесконечности потому что единого мнения ни у кого нету и в нашем случае можно назвать её viewModel). изначально UI в андроиде это хмл файлы. а твои stringkeys это ресурсы. и там им и место. а каждая папка -фрагмент это -экран. 


> > да, фрагмент должны быть внутри где-то. внутри чего? у тебя только один вариант и ты умудряешься его в упор не видеть
> 
> Ну, фрагменты раньше лежали в UI Activity, но ты сказал, что не так

я как раз изначально видел наоборот, только активити и фрагменты вместе на одном уровне. поэтому и доебался

2023-03-10 17:31 UTC, SkirdaD commented
> я как раз изначально видел наоборот, только активити и фрагменты вместе на одном уровне. поэтому и доебался

в самом начале так делал. Уже не суть.

> уже лучше. только фрагмент это не UI, он же человек которые отдельно из полочек собирает. ui это в данном случае холдеры и екстенгшены (по моему, тут можно спорить до бесконечности потому что единого мнения ни у кого нету и в нашем случае можно назвать её viewModel). изначально UI в андроиде это хмл файлы. а твои stringkeys это ресурсы. и там им и место. а каждая папка -фрагмент это -экран.

Я понимаю, что фрагменты должны лежать где-то в активити (по иерархии). А уже сами фрагменты тоже имеют структуру.
Может вся проблема в том, что я оперирую только тремя видами папок (Domain, UI, Data)? Поэтому и путаница?

2023-03-11 17:33 UTC, russabit commented
> Может вся проблема в том, что я оперирую только тремя видами папок (Domain, UI, Data)? Поэтому и путаница?

видимо да

2023-03-11 17:36 UTC, SkirdaD commented
> > Может вся проблема в том, что я оперирую только тремя видами папок (Domain, UI, Data)? Поэтому и путаница?
> 
> видимо да

Так дай мне еще папок)))

2023-03-11 17:44 UTC, russabit commented
> > > Может вся проблема в том, что я оперирую только тремя видами папок (Domain, UI, Data)? Поэтому и путаница?
> > 
> > 
> > видимо да
> 
> Так дай мне еще папок)))

рано ещё, зря вообще я про всё это начал (это уже самый высший пилотаж), потом как понимание придёт будешь раскладывать, щас главное иерархию соблюдай и по какой-нибудь логике организуй, например просто по экранам типа "-screen"

2023-03-11 17:55 UTC, SkirdaD commented
> > > > Может вся проблема в том, что я оперирую только тремя видами папок (Domain, UI, Data)? Поэтому и путаница?
> > > 
> > > 
> > > видимо да
> > 
> > 
> > Так дай мне еще папок)))
> 
> рано ещё, зря вообще я про всё это начал (это уже самый высший пилотаж), потом как понимание придёт будешь раскладывать, щас главное иерархию соблюдай и по какой-нибудь логике организуй, например просто по экранам типа "-screen"

Можно поместить все фрагменты в папку "MainActivityFragments"

2023-03-14 23:27 UTC, russabit commented
> Можно поместить все фрагменты в папку "MainActivityFragments"

и какая там будет иерархия ? где тогда мэйнактивити будет лежать?

2023-03-15 05:59 UTC, SkirdaD commented
> > Можно поместить все фрагменты в папку "MainActivityFragments"
> 
> и какая там будет иерархия ? где тогда мэйнактивити будет лежать?

У каждого фрагмента будет Domain и UI. А мэйнАктивити будет лежать в самом корне

2023-03-15 06:42 UTC, russabit commented
> > > Можно поместить все фрагменты в папку "MainActivityFragments"
> > 
> > 
> > и какая там будет иерархия ? где тогда мэйнактивити будет лежать?
> 
> У каждого фрагмента будет Domain и UI. А мэйнАктивити будет лежать в самом корне

ты же сказал выше что все фрагменты будут в  одной папке. тогда как у каждого будет по две папки своих? набросай как это будет, обсудим

2023-03-15 18:55 UTC, SkirdaD commented
> > > > Можно поместить все фрагменты в папку "MainActivityFragments"
> 
> > > 
> 
> > > 
> 
> > > и какая там будет иерархия ? где тогда мэйнактивити будет лежать?
> 
> > 
> 
> > У каждого фрагмента будет Domain и UI. А мэйнАктивити будет лежать в самом корне
> 
> 
> 
> ты же сказал выше что все фрагменты будут в  одной папке. тогда как у каждого будет по две папки своих? набросай как это будет, обсудим 

Вот смотри. Если забыть про те папки, про которые ты говорил, то я бы оформил структуру так. Черные прямоугольники это папки. ![image](https://user-images.githubusercontent.com/121316397/225414127-ffad2381-2048-4852-b5bd-37afc1911cd2.jpeg)

2023-03-15 19:00 UTC, SkirdaD commented
По мне, это самая логичная структура. Есть мэйнАктивити, которая использует холдер, посредством которого, мы показываем фрагменты. Вот папка с фрагментами, которые есть у мэйнАктивити. Заходим в папку всех фрагментов, а там каждый фрагмент в отделной папочке. Заходим в нужный фрагмент, там лежит джава файл этого фрагмента, а рядом в папочке, всё, что к этому фрагменту относится.

2023-03-16 00:25 UTC, russabit commented
> По мне, это самая логичная структура. Есть мэйнАктивити, которая использует холдер, посредством которого, мы показываем фрагменты. Вот папка с фрагментами, которые есть у мэйнАктивити. Заходим в папку всех фрагментов, а там каждый фрагмент в отделной папочке. Заходим в нужный фрагмент, там лежит джава файл этого фрагмента, а рядом в папочке, всё, что к этому фрагменту относится.

отличный вариант. только вместо листка мог бы в студии перенести и показать мне скрин, и быстрее и нагляднее

2023-03-16 05:50 UTC, SkirdaD commented
> > По мне, это самая логичная структура. Есть мэйнАктивити, которая использует холдер, посредством которого, мы показываем фрагменты. Вот папка с фрагментами, которые есть у мэйнАктивити. Заходим в папку всех фрагментов, а там каждый фрагмент в отделной папочке. Заходим в нужный фрагмент, там лежит джава файл этого фрагмента, а рядом в папочке, всё, что к этому фрагменту относится.
> 
> 
> 
> отличный вариант. только вместо листка мог бы в студии перенести и показать мне скрин, и быстрее и нагляднее

С карандашом и листом лучше думается)

Еще можно Активити холдер и стрингс перенести в UI и рядом с активитимэйн положить

2023-03-21 15:08 UTC, SkirdaD commented
Сделал список. Пока без БД. На БДхелпер не смотри, я забыл убрать его из коммита.

2023-03-25 10:29 UTC, SkirdaD commented
Смотри.

2023-03-25 14:48 UTC, russabit requested changes
внутри коммита комменты

2023-03-25 14:48 UTC, russabit commented on app/src/main/java/slirdad/calculator/Data/DataBase/HistoryDataBaseManager.java
> +    // вот тут у тебя самая большая ошибка - почему кто-то другой (активити и два фрагмента)
смотри последний мой коммит, прямо в студии можешь открыть комменты тебе подсветит если выберешь "показать разницу", их удаляй и на место них отвечай там же и исправляй код, попробуем так потому что наш ПР стал слишком большим и проще всё в студии пока что делать

2023-08-07 18:36 UTC, merged