Issue_3_fix_variable_commenting
SkirdaD/Calculator pull request #6
Opened 2023-01-23 19:32 UTC by SkirdaD

Вот ветка для issue #3.
Я пока только сделал комменты на переменные. 
Не знаю, ты это имел в виду или нет.

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    int lastOperation = NULL;
отлично, то есть, ласт оперейшн может быть одним из нижеследующих интов?

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    int lastOperation = NULL;
раз у тебя lastOperation типа инт, получается мы можем в любом месте кода написать lastOperation = 1248127 ?

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используется в ::changeSizeText.
это я и хотел от тебя услышать. если он 

> Используется в ::changeSizeText.

то зачем эти переменные являются публичными полями активити и торчат наружу?

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
>      final String SAVE_TEXT = "save text";
у тебя непоследовательно эта стринга содержит пробел, а остальные написаны кэмэлКейсом

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используются только в них.
то же самое, торчат наружу из активити, а используются внутренними методами активити.

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +            Я бы, наверное, эту операцию поместил бы в отдельный метод.
есть такой подход, называется самодокументируемый код, когда он написан настолько просто, понятно и чисто, что комментарии не нужны. вынесение такого метода в отдельный как раз сделает шаг в эту сторону, потому что тебе само название этого метода будет объяснять что он делает

2023-01-24 13:27 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
>      Button buttonNum1, buttonNum2, buttonNum3, buttonNum4, buttonNum5, buttonNum6, buttonNum7,
а эти переменные почему пропустил???????

2023-01-24 18:00 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    int lastOperation = NULL;
Получается можем)
Ты ведешь к Энамам?

2023-01-24 18:02 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используется в ::changeSizeText.
То есть их нужно засунуть в сам метод и сделать private и final?

2023-01-24 18:03 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
>      final String SAVE_TEXT = "save text";
Исправил.

2023-01-24 18:07 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используются только в них.
Изменил с final на final private

2023-01-24 18:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
>      Button buttonNum1, buttonNum2, buttonNum3, buttonNum4, buttonNum5, buttonNum6, buttonNum7,
Баттоны? 
Ну а что о них писать) Инициализируются в основном теле и используются:
 -  в онкрейт для нахождения соответствующей вьюхи
 - в списке для последующего вешания на него лисенера

2023-01-24 18:53 UTC, SkirdaD commented
По поводу твоего "Попался")))
Попался! То есть вьюшки тоже должны быть приватными? Да и вообще, всё должно быть максимально закрытым, насколько это возможно?

2023-01-24 22:20 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    int lastOperation = NULL;
а с энамами мы сможем левый инт присвоить?

2023-01-24 22:22 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используется в ::changeSizeText.
вместо такого теоретического вопроса в следующий раз сделай это сразу, закоммить и спрашивай так ли надо было сделать

2023-01-24 22:22 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используются только в них.
где?

2023-01-24 22:24 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
>      Button buttonNum1, buttonNum2, buttonNum3, buttonNum4, buttonNum5, buttonNum6, buttonNum7,
а где этот список находится? какая обсласть видимости??

2023-01-24 22:24 UTC, russabit commented
> По поводу твоего "Попался"))) Попался! То есть вьюшки тоже должны быть приватными? Да и вообще, всё должно быть максимально закрытым, насколько это возможно?

бинго, наконец-то

2023-01-28 01:38 UTC, russabit commented
> По поводу твоего "Попался"))) Попался! То есть вьюшки тоже должны быть приватными? Да и вообще, всё должно быть максимально закрытым, насколько это возможно?

с областью видимости ты же всегда сам выбираешь что использовать - в твоём случае дефолт ты поставил от балды я так понимаю, но в целом спроси себя, нужно чтобы эти вьюшки дёргал кто-то другой, или они только внутри одной активити?

2023-01-28 15:48 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    int lastOperation = NULL;
Думаю, что нет. Ведь присвоить можно только из перечня энама.

2023-01-30 00:56 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
>  import android.widget.Toast;
про это писал

2023-01-30 00:56 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
> +    protected double var2;
про это тоже

2023-01-30 00:57 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
>                      /*Toast.makeText(getApplicationContext(),
этот коммент тебя подвёл

2023-01-30 00:58 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +import android.widget.Toast;
если где-то прибыло, значит надо было проверить что где-то убыло

2023-01-30 00:58 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.
надеюсь теперь понимаешь

2023-01-30 01:00 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        //локальные переменные нет смысла делать константами
это неверно, писал про это

2023-01-30 01:01 UTC, russabit commented on app/src/main/java/slirdad/calculator/StringKeys.java
> +class StringKeys {
здесь молодец, первый класс без ошибок, так держать!

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/Calculation.java
> +    protected double var2;
Ты про что?

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/Calculation.java
>                      /*Toast.makeText(getApplicationContext(),
Почему?

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +import android.widget.Toast;
Да, я не удалил импорт в Калькуляторе

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/Calculation.java
>                      /*Toast.makeText(getApplicationContext(),
Надо было написать, что в МэйнАктивити?

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.
Ты про файнл? Или про экземпляр класса?
Если про экземпляр, то понял. Если про файнл, то не понял.
Если мы будем с него только считывать переменные, то можно и файнл. Но у меня там где-то что-то сетилось.

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        //локальные переменные нет смысла делать константами
Что неверно? Не понимаю к какому коду ты это пишешь

2023-01-30 17:29 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/StringKeys.java
> +class StringKeys {
Да уж... пиздец я охуенный))

2023-01-30 17:30 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +    Используются только в них.
уже нигде

2023-01-31 01:09 UTC, russabit requested changes

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
> +    protected double var2;
про протектид в предыдущем коммите отписывался

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
>                      /*Toast.makeText(getApplicationContext(),
то что ты когда его писал у тебя импортнулось `import android.widget.Toast;` (писал выше), а потом закомментил и у тебя остался этот импорт висеть, "подвёл" - в смысле видно как ты сделал эту ошибку

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.
коммент я оставляю к конкретной строчке выше, в этом случае это 25: 

> И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.

я тебе про файнал писал в комментах к прошлому коммиту, и если ты их прочитал, то 

> надеюсь теперь понимаешь

у тебя в 27 строке что происходит, помнишь ты просил меня тебя спрашивать как Антона, вот ответь сейчас подробно, разберёмся почему здесь подойдёт файнал

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/Calculation.java
> +    protected double var2;
резолв ты отмечаешь когда комментарий исправлен, а в данном случае он ещё висит

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        //локальные переменные нет смысла делать константами
опять, к той строке под которой коммент, привый к этому:

> //локальные переменные нет смысла делать константами

ты читал мои предыдущие комменты из прошлого коммита про константы и переменные? в данном случае 559-563 у тебя сейчас написаны локальные переменные. ты написал что 

> нет смысла делать константами

их значения у тебя меняются в рантайме? я что-то не вижу, что они сеттятся другими значениями потом. значит они не изменяются. а если они не изменяются, то какие они переменные?

2023-01-31 01:09 UTC, russabit commented on app/src/main/java/slirdad/calculator/StringKeys.java
> +class StringKeys {
давай не ругаться тут особо, пиши такое в личку, может потом будем показывать эту репу потомкам ))

2023-01-31 01:12 UTC, russabit commented
давай бери за правило быстро исправлять мелкие вещи которые ты точно понимаешь (как импорты и т.п.) сразу как прочитал мои комменты, чтобы оне не отнимали много времени и я не ждал их столько же, сколько я жду остальные исправления побольше

2023-01-31 17:54 UTC, SkirdaD commented
> давай бери за правило быстро исправлять мелкие вещи которые ты точно понимаешь (как импорты и т.п.) сразу как прочитал мои комменты, чтобы оне не отнимали много времени и я не ждал их столько же, сколько я жду остальные исправления побольше

Я так и делаю. Но ты, наверное говоришь про коммит?

2023-01-31 17:55 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/Calculation.java
> +    protected double var2;
Я так и делаю. Исправил - резолв. И да, я понял, что нужен коммит

2023-01-31 18:04 UTC, SkirdaD commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.
Calculator calculator = new Calculator();
Создается экземпляр класса Калькулятор с именем  calculatior.
Кажется я понял: объект сalculator создался и в принципе с ним больше ничего не произойдет (я не засечу в него какой-то новый объект). А то, что у него будет меняться внутреннее состояние это уже к месту дела не имеет.

2023-01-31 20:01 UTC, SkirdaD commented
Смотри... Вопрос у меня созрел.
Сейчас у меня листенере кнопок операций практически один и тот же код. Причем довольно громоздкий.
Вопрос в том, как правильнее сделать. Много самодокументируемых методов или один, но большой?
Если один, то не понимаю как его корректно назвать.
Один маленький самодокументируемый я уже сделал. Это ::checkForDivideByZeroError.

Вообще, я думаю, что листенеры будут выглядеть внутри так: метод или методы  с определенными входными данными.

2023-01-31 20:05 UTC, SkirdaD commented
Я сейчас сделаю коммит. Как мне его назвать? Когда было всё по пунктам, то было понятно Commit_issue1_fix_1_3_5.
А сейчас я не понимаю, как отразить в названии суть изменений. 
Issue_3_continue_refactoring_v2 ?

2023-02-01 00:22 UTC, russabit commented on app/src/main/java/slirdad/calculator/MainActivity.java
> +        И студия пишет, что может быть файнл. Не стал делать, т.к не понимаю пока этого.
да, правильно, везде где не перемененая не сеттится больше одного раза можно ставить файнал

2023-02-01 03:39 UTC, merged

2023-02-01 03:39 UTC, russabit commented
фундаментальные вещи сделали, нейминг потом поправим, далее базовые вещи, листенеры в конце